### PR TITLE
Add `export snapshot to s3 storage`

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Exporting snapshot to s3 storage is implemented.
- Update docs.
- Update README.

### CODE REVIEW

**Review by bkircher — CHANGES_REQUESTED** [review]
For the code changes: LGTM. Can you also add lines to the changelog?

**Comment by bkircher** [comment]
As for the documentation and strings, they are in line with https://my.gridscale.io/Expert/Documentation for that end-point but are, well, not really correct and already different in the panel.

I think

- S3 should be object store (S3 is really a product name)
- filename should be object
- and a little bit more docs about the `private` member would be helpful, too

@MarcHarriss, what do you think?

**Comment by nvthongswansea** [comment]
> As for the documentation and strings, they are in line with https://my.gridscale.io/Expert/Documentation for that end-point but are, well, not really correct and already different in the panel.
> 
> I think
> 
> * S3 should be object store (S3 is really a product name)
> * filename should be object
> * and a little bit more docs about the `private` member would be helpful, too
> 
> @MarcHarriss, what do you think?

I use the names and fields of the request's body in here https://ce85b99cc46752fffee35cab9a7b0278abb4c2d2055cff685af4912c49490f8.gos3.io/index.html#operation/StorageRollback

**Comment by nvthongswansea** [comment]
> For the code changes: LGTM. Can you also add lines to the changelog?

I will add to the changelog after this PR (all latest changes will be included in a different PR).

**Comment by bkircher** [comment]
🤞

**Pull request merged**
