### PR TITLE
Fix bugs in `server` resource implementation.

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Fix bug causing nil pointer error.
- Add missing resource properties.
- Update `server` resource docs.

### CODE REVIEW

**Comment by itakouna** [comment]
[fix-inmemoy-list.txt](https://github.com/terraform-providers/terraform-provider-gridscale/files/3841106/fix-inmemoy-list.txt)
The objective of keeping a list of servers is that avoiding the concurrency with Terraform process. Thus, I don't think that we need to keep the list shared between different Terraform processes (e.g, store status in a file). Furthermore, we can get the data that sored in `listServersPowerStatus` by calling the API. I attached a patch for the commit 8fcd84f. The patch keeps using the `lock` to avoid concurrency within the Terraform process, but it does not need to keep any listServersPowerStatus inventory.

**Comment by itakouna** [comment]
@nvthongswansea ^^

**Comment by nvthongswansea** [comment]
> [fix-inmemoy-list.txt](https://github.com/terraform-providers/terraform-provider-gridscale/files/3841106/fix-inmemoy-list.txt)
> The objective of keeping a list of servers is that avoiding the concurrency with Terraform process. Thus, I don't think that we need to keep the list shared between different Terraform processes (e.g, store status in a file). Furthermore, we can get the data that sored in `listServersPowerStatus` by calling the API. I attached a patch for the commit [8fcd84f](https://github.com/terraform-providers/terraform-provider-gridscale/commit/8fcd84f252e2938b8c5150044ca25c91ced6b461). The patch keeps using the `lock` to avoid concurrency within the Terraform process, but it does not need to keep any listServersPowerStatus inventory.

Thanks for the hint. Now, we fetch data from API instead of reading from a local file :D

**Comment by itakouna** [comment]
@nvthongswansea have u seen the attached txt file fix-inmemoy-list.txt?

**Comment by nvthongswansea** [comment]
> @nvthongswansea have u seen the attached txt file fix-inmemoy-list.txt?

I am about to use this way (currently coding). The initial solution was that the list would contain a number of `mutex` locks corresponding to number of servers. So that we could process each server in each process, that makes `terraform apply` faster. However, it is much complicated than using a global `mutex` lock in term of development, so I decided to sacrifice performance to gain simplicity. As a result, only one `server` resource can be processed at a single time. If you @itakouna have already implemented, could you commit it here please? Thanks!

**Comment by nvthongswansea** [comment]
Close it because I am trying another way to deal with concurrency.

**Pull request closed without merging**
