### PR TITLE
Add paas security zone

### PR DESCRIPTION
**Pull request by nvthongswansea**

### CODE REVIEW

**Review by itakouna — APPROVED** [review]

**Comment by itakouna** [comment]
@nvthongswansea plz fix conflict

**Comment by nvthongswansea** [comment]
> @nvthongswansea plz fix conflict

Done!

**Comment by itakouna** [comment]
@nvthongswansea another conflict :)

**Comment by nvthongswansea** [comment]
> @nvthongswansea another conflict :)

Done again!

**Review by itakouna — APPROVED** [review]

**Pull request merged**
