### PR TITLE
Fix Bug #109

### PR DESCRIPTION
**Pull request by nvthongswansea**
- Fix bug #109 
- Update the acceptance test for paas service.
- Update gsclient-go package.

### CODE REVIEW

**Review by bkircher — APPROVED** [review]
LGTM

**Comment by bkircher** [comment]
Opsie. Test failed

**Comment by nvthongswansea** [comment]
@bkircher Due to the issue, our backend block PaaS DELETE request sent from user-agent header with value "gsclient-go/". Error "Deletion of platform services is currently not available for your client due to an issue in the terraform provider. A fix to the terraform provider will be provided shortly. Until then, platform services can still be removed in your panel. Sorry for the inconvenience.."

**Review by bkircher — APPROVED** [review]

**Comment by bkircher** [comment]
Yep. Let's merge then (disregard of TestAccdataSourceGridscalePaaS_basic).

**Pull request merged**
